
export const actionTypes = {
	GET_DATA_SUCCESS: 'GET_DATA_SUCCESS',
	SET_LOADING: 'SET_LOADING',
	GET_DATA_ERROR: 'GET_DATA_ERROR',

	GET_COUNTRY_INFO: 'GET_COUNTRY_INFO',
	SEARCH_COUNTRY: 'SEARCH_COUNTRY',
	RESET_FILTERED_DATA: 'RESET_FILTERED_DATA',
	SORT_COUNTRY_LIST: 'SORT_COUNTRY_LIST',
	SORT_TOTAL_LIST: 'SORT_TOTAL_LIST',

	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	GET_COUNTRY_DATA_ERROR: 'GET_COUNTRY_DATA_ERROR',
	SET_MODAL_LOADING: 'SET_MODAL_LOADING'
}